version: '3.9'
services:
  postgres:
    container_name: postgres-local-common
    image: arm64v8/postgres
    environment:
      POSTGRES_USER: mixamus
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'